"""init users and santri with uuid

Revision ID: d106442eb02d
Revises: 
Create Date: 2025-12-27 09:49:42.724104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd106442eb02d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santri',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ekonomi', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('lokasi', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Index creation is handled separately after table creation
    # op.create_index('idx_santri_lokasi', 'santri', ['lokasi'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # PostGIS tables are managed by the extension, skip dropping them
    # op.drop_table('topology')
    # op.drop_table('layer')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostGIS tables are managed by the extension, skip recreating them
    # op.create_table('spatial_ref_sys', ...)
    # op.create_table('layer', ...)
    # op.create_table('topology', ...)
    op.drop_table('users')
    # op.drop_index('idx_santri_lokasi', table_name='santri', postgresql_using='gist')
    op.drop_table('santri')
    # ### end Alembic commands ###
